import { getSession } from "next-auth/react"
import SessionProvider from "@/components/SessionProvider";
import {TokenProvider} from "@/components/TokenProvider";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = getSession()
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
